ts.plot(lynx)
title("Canadian lynx trapping (1821-1934)")
pause()
cat("Data are now log-transformed\n")
log.lynx <- log(lynx)
sm.ts.pdf(log.lynx, lags=4:5)
pause()
sm.autoregression(log.lynx, maxlag=5, se=TRUE)
pause()
sm.autoregression(log.lynx, lags=cbind(4,5))
