with(tephra, {
logit <- log(Al2O3/(100-Al2O3))
nn    <- nnbr(logit, 7)
hw    <- nn/exp(mean(log(nn)))
sm.density(logit, h.weights = hw, lty = 2, yht = 12.2)
hw    <- sqrt(nn)
hw    <- hw/exp(mean(log(hw)))
sm.density(logit, h.weights = hw, lty = 3, add = TRUE)
sm.density(logit, add = TRUE)
})
